#!/bin/sh
case "$1" in
    configure)
	adduser --system --shell /bin/bash --home /var/lib/plexmediaserver plex
	service plexmediaserver restart
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0

